### ISSUE TITLE
Resume when using multiple Records

### ISSUE THREAD

**Issue by apoleo88** [llfbandit/record#11]
Hi! Great work! I like this library because it is simple to use!

Unfortunately, I need a functionality that conflicts with this characteristic.

I need to have multiple open audio records on one page.

I would like to be able to pause and resume each of them.

Start 1°
Pause 1°
Start 2°
Pause 2°
Resume 1°

Unfortunately, it seems that there is only one static instance `Record.Start(..)`

is there any solution for this? 
Like a flag on `Record.Start(..., resume_on_file: true)`, so it could append to the already stored file?

**Comment by llfbandit** [comment]
Thanks for your support !

Unfortunately, you can't with the current implementation as you discovered. You're right this plugin was made to fulfill my needs at start with easy approach and it's now kind of limitation.
I'm thinking to revamp static access to instances to better suit pending requests like yours.

**Comment by apoleo88** [comment]
I will stay tuned for updates, but I agree on the main purpose, and stay simple! : )

**Comment by llfbandit** [comment]
After searching, creating multiple instances of audio session, is very risky.

Both platforms (iOS and Android) are not specifying any support on this.
Also, there's many reports of failures (or crashes) when attempting to use more than one media recorder (... or it may work depending of the device). This is mostly due to limited device hardware and/or software resources like codecs.

So, finally, I won't be able to implement this if there's no support of native SDKs.
Sorry for the bad news.

**Comment by apoleo88** [comment]
it is possible instead to attach the new record to an existing file?

So, when it pauses, it closes the audio session, saves the file, and starts a new audio session for the second record.

When you want to resume the first one, it will open a new audio session, then on save it will append the audio to the already saved file specified in the constructor.

In this scenario, there always be one audio session open at a time.
