### ISSUE TITLE
Issues with stopping audio recording on android

### ISSUE THREAD

**Issue by hu1006462702** [llfbandit/record#187]
**Package version**
5.0.0-beta.2

**Describe the bug**
The file size obtained after calling _audiorecord.stop () is 209964, and the file size is 212992 after 100 mm

**Smartphone (please complete the following information):**
 - Device: [1+ 11]
 - OS: [Android 13]

**Comment by llfbandit** [comment]
I don't understand the issue.

**Comment by hu1006462702** [comment]
After calling await _audiorecord.stop (), the size of the returned file will not be the same as the size of the file obtained at 100 ms.

**Comment by hu1006462702** [comment]
var path = await _audiorecord.stop ()

Read the file immediately. The file is corrupted and unplayable

**Comment by llfbandit** [comment]
Yes, you must rely on state stream because the encoder has not yet finished to fill the file.
`stop` method is acting as a signal to stop the recording on most platforms. While the gap is thin, it still exists but I don't wan't to block the call (which would require quite of lines of code) for few ms.
