### ISSUE TITLE
Recording voice failure due to different Sample Rates

### ISSUE THREAD

**Issue by BrianMwas** [llfbandit/record#224]
**Package version**
5.0.0

**Describe the bug**
Unable to record voice due to the following error: Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported.

**To Reproduce**
1. Add the record dependency
2. Implement the start record functionality with WAV format
4. See error on the web console. Particularly Firefox

**Expected behavior**
Get a suitable path for the recorded audio

**Comment by llfbandit** [comment]
Thanks for the report.
The issue is somewhat fixed in record_web 1.0.1.

Firefox does not support resampling feature and sample rate is set by the browser at 48kHz.
WAV & PCM outputs are impacted by this. Sample rate config is ignored in such case.

https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/sampleRate

**Comment by llfbandit** [comment]
record_web 1.0.2 has fixes with audio thread too and adds acceptable resampler for firefox and others that may not support sampleRate constraint.
