### ISSUE TITLE
Recording not working (saving?) on iOS

### ISSUE THREAD

**Issue by pssoor** [llfbandit/record#235]
**Package version**
^5.0.1

**Describe the bug**
The code I am using to start the recorder is: 

   if (await widget.audioRecorder.hasPermission()) {
          await widget.audioRecorder
              .start(const RecordConfig(), path: filePath);

        } else {
          await widget.audioRecorder.stop();
        }

This works perfectly on Android (device connected to MacBook), but when I have my iPhone connected, nothing happens. No message in the console whatsoever. 

I have another function which uses the code: 

beingRecorded = await widget.audioRecorder.isRecording();
print(beingRecorded);

This actually prints true, but the file does not actually save anywhere and as previously mentioned, there is no debug log being printed to explain any error.

**To Reproduce**
Install latest version of 'record' package.
Use code as displayed above (or in the readme.md)

**Expected behavior**
Audio file should be recorded and saved.

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.1

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS: 17.1

**Additional context**
I had to revert back to ^4.4.4 for it to work again. I'm not yet experienced or knowledgeable enough to try and submit a pull request for this!

**Comment by llfbandit** [comment]
Does you path come from path_provider?
In v5 there's no temporary file path generated.

**Comment by pssoor** [comment]
Hiya, thanks for responding!

No the 'filePath' is just a String variable which I have created beforehand which is used in widget.audioRecorder.start.

Not using path_provider here.

Please let me know if there's anything else I can provide - I'll keep trying different things on my end

**Comment by llfbandit** [comment]
Be sure to provide a valid path so use path_provider. I don't need anything else. You can also have a look to the sample to help you for this.
For now the issue is still invalid.

**Comment by pssoor** [comment]
So just to be clear, this is what I'm running prior to starting the audioRecorder.start function:

  String filePath = "";

  setFilePath() async {
    final Directory tempDir = await getApplicationDocumentsDirectory();
    String appDocPath = tempDir.path;

    String dateTime = ref.read(dateAndTime.notifier).state;

    if (widget.condition != null) {
      filePath =
          "$appDocPath/${widget.stationSubtitle} ${widget.stationTitle} ${widget.condition!.name} $dateTime.aac";
    } else if (widget.consult != null) {
      filePath =
          "$appDocPath/${widget.stationSubtitle} ${widget.stationTitle} ${widget.consult!.name} $dateTime.aac";
    }
  }

I run the setFilePath in the initState method.


I have used the print(filePath) and found that the filePath is correct - as I mentioned, it works absolutely fine on Android, just not on a connected iPhone/iPad, which is what I couldn't understand. The info.plist file has the microphone permission as well. When I reverted down to 4.4.4, it works, and the only change in code that I need to make is changing AudioRecorder to Record and removing the RecordConfig parameter.

Sorry if I sound like I'm complaining - I am very grateful for the package!

**Comment by blokberg** [comment]
I had the same problem and had to go back to version 4.4.4.

I think, the difference between version 4.4.4 and 5.0.1 is the file path.

In version 4.4.4 the file path starts with the string `"file:///"`.
In 5.0.1 there is no `"file:///"` in string.
For example (for ios),
4.4.4 File path: `"file:///private/var/mobile/Containers/...."`
5.0.1 File path: `"/private/var/mobile/Containers/...."`

And without the string "file:////" the audio players cannot play the audio file.
Actually the `"_player.setSource(path)"` (or something like) method throws an error.
(I only tried the ["just_audio"](https://pub.dev/packages/just_audio) and ["audioplayers"](https://pub.dev/packages/audioplayers) packages).

I reverted to version 4.4.4 because I didn't think that manually adding `"file:///"` to the beginning of the file path would be a permanent solution.

Regardless of the above issue, if you revert to version 4.4.4 and want to delete the file with the `"file.delete()"` method, you may get a _"No such file or directory"_ error.

Unfortunately, the file you created using "File(path)" with a file path starting with the string "file:////" cannot be deleted with the "file.delete()" method.

You can overcome this problem by adding a check like `"if(path.contains('file://'))"` and then deleting "file://" from the string and creating a new file.

```
if (file.path.contains('file://')) {
    String newPath = file.path.replaceAll('file://', '').trim();
    File f = File(newPath);
    await f.delete();
}
```

Sorry for my bad English.
I hope, helps someone.

**Comment by llfbandit** [comment]
With audioplayers you need to use `DeviceFileSource` or other. Also, you can use `Uri.file(path)` if you need an uri with file scheme.
The package now gives the concrete path because some may use it for other purpose.

**Comment by blokberg** [comment]
I tried `"DeviceFileSource"` for the `"audioplayers"` package before and it didn't work.

Probably because I passed the file path as a parameter for the audio player without changing it as returned from the `"_audioRecorder.stop()"` method. Or I missed something else.

But when I pass the file path as `"Uri.file(path)"` as you said, it worked perfectly.

For `just_audio` package example:
```
import 'package:just_audio/just_audio.dart' as ap;

ap.AudioSource? _audioSource;
.
.
.
_audioFilePath = await _audioRecorder.stop();
_audioSource = ap.AudioSource.uri(Uri.file(_audioFilePath));
```

So I got rid of the confusion when deleting a file.

Thank you for teaching me something new and for your time.
