### ISSUE TITLE
Support for outputting shards of recorded files without stopping the recording

### ISSUE THREAD

**Issue by willxie** [llfbandit/record#241]
**Is your feature request related to a problem? Please describe.**

Today, the recorder needs to be stopped before a file can be outputted. For a long recording, it's often infeasible to send over a large file over the net. I was hoping that incremental 1 minute compressed `.mp3` can be generated for a long 30 minute recordings. So 30 `.mp3`s in total that can be incrementally sent to the server and let the server stitch them back together if needed. 

I understand that there's a stream function for raw, uncompressed audio data. But these will be large in size without additional post processing. Ideally we can use the same library to generate these shards as if they were individually "stopped" recordings

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
Use streamed data and do post processing like converting to `.mp3` to shrink the size. However, they code will be messy for cross-platform support. The above suggested solution should be much simpler by just using the same encoder and implementation based on the platform.

**Comment by llfbandit** [comment]
Unfortunately, there's no workaround that can be implemented in the package right now.
The only solution from this package is to use aac/adts but this is only available for Android at this time (and I don't how to achieve this on other platforms).
Otherwise, you can still shard the file before uploading it. 
Streaming current recording can not be done because file is open with random access flag. So we can't be sure that data is right when polling it.
