### ISSUE TITLE
Trying to stream PCM16 over websockets to Google's Speech-to-Text API results in a jumbled mess.

### ISSUE THREAD

**Issue by BambooRaptor** [llfbandit/record#286]
**Package version: ^5.0.4**

**Environment**
 - OS: Android/iOSl

**Describe the bug**
I am trying to use the `record` library to transcribe audio in realtime. I want to send the stream of audio in PCM16 format over websockets to a custom server, which will then send it to a Speech-to-Text service. However, doing a `stream.listen` on
```dart
final AudioRecorder _recorder = AudioRecorder();

final stream = await _recorder.startStream(const RecordConfig(
    encoder: AudioEncoder.pcm16bits,
    sampleRate: 48000,
));
```
returns a `Uint8List` which does not work well since the service expects PCM16 to be a 16bit list.
So far, I have tried `_recorder.convertBytesToInt16(chunk)`, a for loop that just sends the data one 8bit int at a time, `chunk.buffer.toInt8List()`, and just sending the `chunk.buffer` as is, but nothing has worked.

**Expected behavior**
Ideally, the resulting stream from the PCM16 encoding should be an Int16List to reflect the true nature of the data, but this oversight seems to be there in all the recording libraries for some reason. How could I go about solving this? How can I extract the 16 bit integers for PCM16 from this `Uint8List`?

**Comment by austibwu** [comment]
I'm not sure this applies to raw pcm data because I'm only starting out and have only worked with .wavs but:
wav (pcm format with information headers) is always stored in 8bit ints, and the headers inform the reader how to interpret those 8bit ints (i.e. if the data was recorded at 32bitdepth, it would parse 4 ints at a time to re-create a single sound sample). For 16bitdepth data to be streamed as 8bit, the samples must be getting split into 8bit ints before being streamed out. \*\*IF** this is the case, you would need to take two 8bit ints and parse (little endian) to a 16bit int. 

```
int sample = ByteData.view(
     Int8List.fromList(<first 8bit int>, <second 8bit int>).buffer)
     .getInt16(0, Endian.little);
```

there's probably a cleaner way to do that, but it's approximately how my code looks when I'm doing conversions.

However, in my own time experience trying to output audio clips with this records package, the 16bitpcm does not appear to truly be outputting data at 16bitdepth (i opened my own [issue](https://github.com/llfbandit/record/issues/280) a bit earlier and haven't heard back, not sure if it's just user error on my side). So, before you try any of the above I would politely suggest you verify what format your data is actually outputting as before proceeding.

I also apologize if you already know any of the above information 😅 hope this helps....

**Comment by austibwu** [comment]
deleting my previous comment because it was completely off base- 
@BambooRaptor if you are still working this, try parsing every two int8s into an in16 in little endian. before pushing it to the service.

**Comment by llfbandit** [comment]
Why would you convert bytes to integers (16bits) before sending the stream over network? You can only send bytes.
I guess your issue is more about the sample rate which should be 8kHz or 16kHz, shouldn't it? Or something else that isn't written here.
The stream returns `Uint8List` because it allows to convert it to integers or floats if needed (float (32bits) is not supported at this time).

So far, there's no issue related to this package. Please, use discussion feature for such concern.
