### ISSUE TITLE
Android R8 issue

### ISSUE THREAD

**Issue by salahu01** [llfbandit/record#349]
**Package version**

**Environment**
 - OS: Android

**Describe the bug**

I can't run my flutter project . I am getting error cause of this package . I run after removing this package  and its worked .

**Additional context**

Execution failed for task ':app:minifyDebugWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete, origin: /home/babu/Documents/fegno_project/build/record_android/intermediates/runtime_library_classes_jar/debug/classes.jar:com/llfbandit/record/record/format/Format.class

ERROR:/home/babu/Documents/fegno_project/build/record_android/intermediates/runtime_library_classes_jar/debug/classes.jar: R8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes

**Comment by Aanu1995** [comment]
Same here. I am unable to build the android app when I upgraded to the latest package (5.1.1).

I am using Flutter version 3.22.2

**Comment by xiemei1** [comment]
I got the same error. After removing `record` package, I can build the app.

Flutter version: 3.19.6
JDK: openjdk 17
gradle: 7.2
jvmTarget: '1.8'

**Comment by Aanu1995** [comment]
> https://github.com/llfbandit/record/blob/master/record_android/README.md

Thank you for the great job you are doing on the payment. I think upgrading the grade version causes a breaking change and the version where the gradle was upgraded should be a major version bump (should be 6.0.0) instead of minor version 5.1.1 which now causes breaking change.

Unfortunately I can't upgrade the gradle version to AGP 8 because I am experiencing other issues due to other packages in my project that are yet to upgrade to AGP 8.

However, downgrading even record package to 5.0.0 is still throwing the error in Android.

**Comment by WXYzing** [comment]
have the same issue.

**Comment by wb-hwang** [comment]
have the same issue.

**Comment by wb-hwang** [comment]
I fixed with this :
```
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.4.1" apply false
}
```
