### ISSUE TITLE
 ... channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread.

### ISSUE THREAD

**Issue by martinmay67** [llfbandit/record#379]
**Package version**
5.1.2

**Environment**
 - OS: Windows

**Describe the bug**
When starting the recorder audio stream, I get the following error in the logs:

`[ERROR:flutter/shell/common/shell.cc(1065)] The 'com.llfbandit.record/eventsRecord/ac553894-2dfd-45aa-b17f-08697d986033' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread.
`
The recording works, but it may cause some problems in the future.

**To Reproduce**

Would you like me to send you a link to the repo with a sample app?

**Expected behavior**

No such error should happen.

**Additional context**

NA

**Comment by venky9885** [comment]
same issue

**Comment by Lonely1371** [comment]
Hello,
I am also encountering this error on the Windows platform with the latest version. It occurs during recording, and nothing is being saved.

[+245842 ms] [ERROR:flutter/shell/common/shell.cc(1065)] The 'com.llfbandit.record/events/1eacebba-7a92-4a55-acae-8c9a0e7663dd' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.

**Comment by llfbandit** [comment]
Workaround has been added. Flutter team should put efforts this year to fix this properly.

**Comment by tonyhoang2712** [comment]
I used commit 37548ed in my project. This error (`[ERROR:flutter/shell/common/shell.cc(1065)] The 'com.llfbandit.record/events/1eacebba-7a92-4a55-acae-8c9a0e7663dd' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.`) no longer appears but when doing build "flutter build windows" the app still crashes.

**Comment by llfbandit** [comment]
@tonyhoang2712 so, is this really due to this issue?
I tried with the example project and everything is OK on my side (windows 11).
