### ISSUE TITLE
Windows Build - Recording is not being saved and player gives this error "AudioPlayers: Error setting url to file path"

### ISSUE THREAD

**Issue by umerazeem-interloop** [llfbandit/record#86]
I have to use this recorder for windows, but when I run it on windows its not working. It doesn't save any file at the path and player gives the above mentioned error. I've test it on web and android and it works fine on these platforms.

I'm hoping to get the feedback on this soon.

**Comment by rehmnabdul** [comment]
I'm getting the same error. Unable to solve this.

**Comment by llfbandit** [comment]
I'm not responsible of audio player. Did you try to open the recorded file with your favorite player? The path is given in the logs.

**Comment by umerazeem-interloop** [comment]
There is no recorded file to be played that's the error. When we run it on windows it doesn't create any recorded file at the given path.

**Comment by rehmnabdul** [comment]
For me, the issue is the recording files are not created or saved on the disk. That's why the player is unable to play it.  There is no special log. Just 2 lines I see on the console. One is about the saved location the file is saved at "folder/24894389.m4a". The second line says the player error is unable to play it which is definitely because the file does not exist.

**Comment by umerazeem-interloop** [comment]
Same issue. I've used the example project from this repo as it is and tested it on windows and its not saving file at the given path. Also the fmedia.exe is there next to executable file after building.

**Comment by llfbandit** [comment]
Fixed record_windows 0.6.1.
